apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crossplane-rbac-manager
  labels:
    prometheus: app-monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: crossplane-rbac-manager
  endpoints:
  - port: web
