apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: providers
  labels:
    prometheus: app-monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: providers
  endpoints:
  - port: web
