apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: crossplane
  namespace: upbound-system
  labels:
    app: crossplane
spec:
  selector:
    matchLabels:
      app: crossplane
  podMetricsEndpoints:
  - port: metrics