apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: crossplane-rbac-manager
  namespace: upbound-system
  labels:
    app: crossplane-rbac-manager
spec:
  selector:
    matchLabels:
      app: crossplane-rbac-manager
  podMetricsEndpoints:
  - port: metrics