kind: Service
apiVersion: v1
metadata:
  name: crossplane
  namespace: upbound-system
  labels:
    app: crossplane
spec:
  selector:
    app: crossplane
  ports:
  - name: http-metrics
    port: 8080
