apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xosss.observe.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: observe.platform.upbound.io/v1alpha1
    kind: XOss

  patchSets:
    - name: common
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.providerConfigRef.name

  resources:
    - name: podMonitorCrossplaneRbacManager
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          labels:
            type: podMonitorCrossplaneRbacManager
        spec:
          forProvider:
            manifest:
              apiVersion: monitoring.coreos.com/v1
              kind: PodMonitor
              metadata:
                name: crossplane-rbac-manager
                namespace: operators
                labels:
                  app: crossplane-rbac-manager
              spec:
                namespaceSelector:
                  matchNames:
                    - crossplane-system
                    - upbound-system
                selector:
                  matchLabels:
                    app: crossplane-rbac-manager
                podMetricsEndpoints:
                - port: metrics
      patches:
        - type: PatchSet
          patchSetName: common

    - name: podMonitorCrossplane
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          labels:
            type: podMonitorCrossplane
        spec:
          forProvider:
            manifest:
              apiVersion: monitoring.coreos.com/v1
              kind: PodMonitor
              metadata:
                name: crossplane
                namespace: operators
                labels:
                  app: crossplane
              spec:
                namespaceSelector:
                  matchNames:
                    - crossplane-system
                    - upbound-system
                selector:
                  matchLabels:
                    app: crossplane
                podMetricsEndpoints:
                - port: metrics
      patches:
        - type: PatchSet
          patchSetName: common

    - name: podMonitorCrossplaneProviders
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          labels:
            type: podMonitorCrossplaneProviders
        spec:
          forProvider:
            manifest:
              apiVersion: monitoring.coreos.com/v1
              kind: PodMonitor
              metadata:
                name: crossplane-providers
                namespace: operators
                labels:
                  app: crossplane-providers
              spec:
                namespaceSelector:
                  matchNames:
                    - crossplane-system
                    - upbound-system
                selector:
                  matchLabels:
                    app: crossplane-providers
                podMetricsEndpoints:
                - port: http-prom
      patches:
        - type: PatchSet
          patchSetName: common

    - name: podMonitorXmetrics
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        metadata:
          labels: 
            type: podMonitorXmetrics
        spec:
          forProvider:
            manifest:
              apiVersion: monitoring.coreos.com/v1
              kind: PodMonitor
              metadata:
                name: x-metrics
                namespace: operators
                labels:
                  app: x-metrics
              spec:
                namespaceSelector:
                  matchNames:
                    - crossplane-system
                    - upbound-system
                    - x-metrics
                selector:
                  matchLabels:
                    app: x-metrics
                podMetricsEndpoints:
                  - port: metrics
                    path: "/x-metrics"
      patches:
        - type: PatchSet
          patchSetName: common

    - name: releasePrometheus
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          rollbackLimit: 3
          forProvider:
            namespace: operators
            chart:
              name: kube-prometheus-stack
              repository: https://prometheus-community.github.io/helm-charts
              version: "52.1.0"
            values:
              prometheus:
                prometheusSpec:
                  serviceMonitorSelectorNilUsesHelmValues: false
                  podMonitorSelectorNilUsesHelmValues: false
                  probeSelectorNilUsesHelmValues: false
                  ruleSelectorNilUsesHelmValues: false
      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: spec.parameters.id
          toFieldPath: metadata.name
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.parameters.operators.prometheus.version
          toFieldPath: spec.forProvider.chart.version
        - fromFieldPath: spec.parameters.id
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          transforms:
            - type: match
              match:
                patterns:
                  - type: regexp
                    regexp: '.*'
                    result: oss

    - name: usagePrometheusByPodMonitorXmetrics
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          of:
            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            resourceSelector:
              matchControllerRef: true
          by:
            apiVersion: kubernetes.crossplane.io/v1alpha1
            kind: Object
            resourceSelector:
              matchControllerRef: true
              matchLabels:
                type: podMonitorXmetrics

    - name: usagePrometheusByPodMonitorCrossplaneRbacManager
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          of:
            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            resourceSelector:
              matchControllerRef: true
          by:
            apiVersion: kubernetes.crossplane.io/v1alpha1
            kind: Object
            resourceSelector:
              matchControllerRef: true
              matchLabels:
                type: podMonitorCrossplaneRbacManager

    - name: usagePrometheusByPodMonitorCrossplane
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          of:
            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            resourceSelector:
              matchControllerRef: true
          by:
            apiVersion: kubernetes.crossplane.io/v1alpha1
            kind: Object
            resourceSelector:
              matchControllerRef: true
              matchLabels:
                type: podMonitorCrossplane

    - name: usagePrometheusByPodMonitorProviders
      base:
        apiVersion: apiextensions.crossplane.io/v1alpha1
        kind: Usage
        spec:
          of:
            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            resourceSelector:
              matchControllerRef: true
          by:
            apiVersion: kubernetes.crossplane.io/v1alpha1
            kind: Object
            resourceSelector:
              matchControllerRef: true
              matchLabels:
                type: podMonitorCrossplaneProviders
